AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket with drift detection support via CloudFormation

Parameters:
  BucketName:
    Type: String
    Description: Base name for the S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-drift-demo-bucket"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: Test
        - Key: Project
          Value: DriftDemo

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the created S3 bucket

  BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: ARN of the created S3 bucket
